// <auto-generated />
using System;
using ManagementAngajati.Persistence.DbUtils;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManagementAngajati.Migrations
{
    [DbContext(typeof(ManagementAngajatiContext))]
    [Migration("20220705135204_myMigration")]
    partial class myMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AngajatEntityPostEntity", b =>
                {
                    b.Property<long>("AngajatiID")
                        .HasColumnType("bigint");

                    b.Property<long>("IdPosturiID")
                        .HasColumnType("bigint");

                    b.HasKey("AngajatiID", "IdPosturiID");

                    b.HasIndex("IdPosturiID");

                    b.ToTable("AngajatEntityPostEntity");
                });

            modelBuilder.Entity("ManagementAngajati.Persistence.AngajatEntity", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"), 1L, 1);

                    b.Property<DateTime>("DataNasterii")
                        .HasColumnType("datetime2");

                    b.Property<int>("Experienta")
                        .HasColumnType("int");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Angajati");
                });

            modelBuilder.Entity("ManagementAngajati.Persistence.Entities.ConcediuEntity", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"), 1L, 1);

                    b.Property<DateTime>("DataIncepere")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataTerminare")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdAngajatID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("IdAngajatID");

                    b.ToTable("Concedii");
                });

            modelBuilder.Entity("ManagementAngajati.Persistence.Entities.IstoricAngajatEntity", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"), 1L, 1);

                    b.Property<long>("AngajatID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataAngajare")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataReziliere")
                        .HasColumnType("datetime2");

                    b.Property<long>("PostID")
                        .HasColumnType("bigint");

                    b.Property<int>("Salariu")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AngajatID");

                    b.HasIndex("PostID");

                    b.ToTable("IstoricuriAngajati");
                });

            modelBuilder.Entity("ManagementAngajati.Persistence.Entities.PostEntity", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"), 1L, 1);

                    b.Property<string>("Departament")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetaliuFunctie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Functie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Posturi");
                });

            modelBuilder.Entity("AngajatEntityPostEntity", b =>
                {
                    b.HasOne("ManagementAngajati.Persistence.AngajatEntity", null)
                        .WithMany()
                        .HasForeignKey("AngajatiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManagementAngajati.Persistence.Entities.PostEntity", null)
                        .WithMany()
                        .HasForeignKey("IdPosturiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ManagementAngajati.Persistence.Entities.ConcediuEntity", b =>
                {
                    b.HasOne("ManagementAngajati.Persistence.AngajatEntity", "IdAngajat")
                        .WithMany("Concedii")
                        .HasForeignKey("IdAngajatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdAngajat");
                });

            modelBuilder.Entity("ManagementAngajati.Persistence.Entities.IstoricAngajatEntity", b =>
                {
                    b.HasOne("ManagementAngajati.Persistence.AngajatEntity", "Angajat")
                        .WithMany()
                        .HasForeignKey("AngajatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManagementAngajati.Persistence.Entities.PostEntity", "Post")
                        .WithMany()
                        .HasForeignKey("PostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Angajat");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("ManagementAngajati.Persistence.AngajatEntity", b =>
                {
                    b.Navigation("Concedii");
                });
#pragma warning restore 612, 618
        }
    }
}
